### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by bluraygun** [MatheusrdSantos/Dino-genetic-algorithm#1]
Your algorithm cannot be run. Executing any of the options you provide results in the following: FileNotFoundError: [Errno 2] No such file or directory: './data/mask/dino_down_mask'

**Comment by sulfrum** [comment]
those files are in the .gitignore, they are not in the repo. So you have to regenerate them by launching generateMaskData.py that you can find in .data/mask/

**Comment by bluraygun** [comment]
Should be stated in README.md then
